name: Update immich-cli

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get latest immich-cli version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s "https://registry.npmjs.org/@immich/cli/latest" | jq -r '.version')
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image exists
        id: check_image
        run: |
          if docker manifest inspect ghcr.io/${{ github.repository_owner }}/docker-immich-cli-curl:${{ steps.get_version.outputs.latest_version }} > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Build and push if new
        if: steps.check_image.outputs.exists == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-immich-cli-curl:${{ steps.get_version.outputs.latest_version }}
            ghcr.io/${{ github.repository_owner }}/docker-immich-cli-curl:latest
          build-args: |
            IMICH_CLI_VERSION=${{ steps.get_version.outputs.latest_version }}
